### ISSUE TITLE
[NOTE] Sony patched this

### ISSUE THREAD

**Issue by PedroxTheBest99** [TheOfficialFloW/h-encore-2#1]
well, it looks like Sony doesn't like us and made the FW version 3.72, that DID patch this out!
Changelog from the official website:
This system software update improves system performance.

Imo, it doesn't make any sense cuz the only thing that revived PS Vita was hacks and homebrews

Sources: https://www.playstation.com/en-us/support/system-updates/ps-vita/ and https://gbatemp.net/threads/ps-vita-firmware-3-72-released-blacklists-bitter-smile-h-encore.546878/

**Comment by TheOfficialFloW** [comment]
Why the heck did you open an issue for that?
