### ISSUE TITLE
Request to support PSV version 3.75

### ISSUE THREAD

**Issue by Sorata** [TheOfficialFloW/h-encore-2#10]
The PSV have a new version 3.75.
Please support it when you have time. Thank you.

**Comment by TheOfficialFloW** [comment]
Source?

**Comment by Sorata** [comment]
Did you mean the PSVUPDAT.PUP? 
Sorry ,this is my first to add issue for h-encore-2.
When I get the 3.75 PSVUPDAT.PUP, I will comment again. Thank you~ Have a nice day.

**Comment by TheOfficialFloW** [comment]
What tf was that.

**Comment by Sorata** [comment]
I'm very very very sorry to disturb you.
It looks like I receive a wrong information. It looks like 3.73 is the newest version now.
Thank you for everything you do for people who love PSV.
Next time, after I have prepared well and checked it correctly, I will come back to ask for your help.
