### ISSUE TITLE
Battery Charging not working after installing h-encore

### ISSUE THREAD

**Issue by LarsMasters** [TheOfficialFloW/h-encore-2#11]
One of the battery charger problems I found after installing h-encore are:

* Unable to connect charge to regular AC adapter
* Unable to connect charge to either regular AC adapter or consoles/PC, when Battery percentage is at Lower Green (or possibly at Medium)

USB Power Supply always on, but still not working

**Comment by TheOfficialFloW** [comment]
Doubt.
