### ISSUE TITLE
3.72 issues

### ISSUE THREAD

**Issue by jarob00** [TheOfficialFloW/h-encore-2#2]
I have installed h-encore-2 on 3.72. vita slim
I am able to access autoplugin and vitashell

adrenaline will not work - gives error c1-2758-2
- I have checked and config.txt has ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx 
- tried installing 6-fix 

sd2vita not working.  
- I have installed storagemgr.skprx
- I have attempted many settings in storage_config.txt
- I am unable to mount internal storage it gives error 0x80010078
- I tried multiple known working adapters

I am able to get either working on another 3.68 Vita and followed the same process without success on 3.72.

**Comment by TheOfficialFloW** [comment]
Both plugins have not been updated yet.
