### ISSUE TITLE
C1-2758-2 When trying to install h-encore via ContentManager

### ISSUE THREAD

**Issue by amkherad** [TheOfficialFloW/h-encore-2#6]
I have done everything multiple times now, but when I try to copy the application from my PC to the vita I keep getting C1-2758-2 error, I tried this on another vita and it worked correctly but I can't get it right on this one.

It's at 3.72 FW, I have enough free storage, and I did everything correctly.

**Comment by zakthompson** [comment]
Hey - not sure why this was closed, but I'm having the same issue with my Vita, PCH-1001 FW 3.73.  I've been through the steps 3 or 4 times and I'm pretty confident I did everything correctly.  Any insight would be much appreciated!
