### ISSUE TITLE
Crashes while open h-encore 2

### ISSUE THREAD

**Issue by Jacoe79** [TheOfficialFloW/h-encore-2#7]
Ps Vita pch-2016
Firmware 3.68
SD2Vita

Everything works perfect, but if my vita is switched off completely or it restarts - 60% of the time h-encore 2 will freeze while opening. The vita will then restart by itself and maybe by the 2nd or 3rd time I will be able to open h-encore 2

**Comment by TheOfficialFloW** [comment]
Next time you better read the FAQ before you open a useless issue.
